tof_serial:
    ros__parameters:
        port: "/dev/ttyACM0"         # arduino port
        baudrate: 2000000            # baudrate for arduino
        cmd_size: 3                  # msg size from linux
        msg_size: 51                 # msg size from arduino
        receive_time: 100            # delay after receiving msg from arduino
        pub_topic: "/serial/tof/pub" # topic name for arduino receiver
        sub_topic: "/serial/tof/sub" # topic name for arduino sender
