FROM althack/ros2:humble-full

# workspace setup

ENV WS="/workspace"
ENV WS_drivers_stm="/microros_ws"

ENV ROS_DISTRO=humble
RUN echo "source ${WS}/install/setup.bash" >> ~/.bashrc
RUN echo "source ${WS_drivers_stm}/install/local_setup.bash" >> ~/.bashrc
RUN echo "cd /workspace" >> ~/.bashrc

# install packages

RUN apt update -y

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
RUN DEBIAN_FRONTEND=noninteractive apt install -y vim emacs nano

RUN python3 -m pip install setuptools==58.2.0

RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-slam-toolbox
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-navigation2
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-nav2-bringup
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-rtabmap-ros

RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-joint-state-publisher-gui

COPY entrypoint.sh /entrypoint.bash
RUN chmod +x /entrypoint.bash

ENTRYPOINT ["/entrypoint.bash"]
