services:
  ros2:
    build: .
    image: ros2_humble

    network_mode: host

    working_dir: /workspace
    volumes:
      - ../workspace:/workspace
      - ./entrypoint_ros2.sh:/entrypoint_ros2.sh

    environment:
      - ROBOT_ID=${ROBOT_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    entrypoint: ["bash", "/entrypoint_ros2.sh"]

    privileged: true

    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped

  ros2-builder:
    build: .
    image: ros2_humble

    network_mode: host

    working_dir: /workspace
    volumes:
      - ../workspace:/workspace

    environment:
      - ROBOT_ID=${ROBOT_ID}

    entrypoint: []

    privileged: true

    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped

  microros:
    build: .
    image: ros2_humble

    network_mode: host

    working_dir: /microros_ws
    volumes:
      - ../microros_ws:/microros_ws
      - /dev/serial:/dev/serial
      - ./entrypoint_microros.sh:/entrypoint_microros.sh

    environment:
      - ROBOT_ID=${ROBOT_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    entrypoint: ["bash", "/entrypoint_microros.sh"]

    devices:
      - "/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0:/dev/ttyUSB0"
      - "/dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_066DFF495277504867215937-if02:/dev/ttyACM0"

    privileged: true

    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped

  microros-builder:
    build: .
    image: ros2_humble

    network_mode: host

    working_dir: /microros_ws
    volumes:
      - ../microros_ws:/microros_ws

    environment:
      - ROBOT_ID=${ROBOT_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    entrypoint: []

    devices:
      - "/dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_066DFF495277504867215937-if02:/dev/ttyACM0"

    privileged: true

    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped
