FROM osrf/ros:humble-desktop-full

# workspace setup

ENV ROS_DISTRO=humble
ENV WS="/workspace"

RUN echo '\
if [ -f "/opt/ros/${ROS_DISTRO}/setup.bash" ]; then\n\
    source "/opt/ros/${ROS_DISTRO}/setup.bash"\n\
fi\n\
if [ -f "${WS}/install/setup.bash" ]; then\n\
    source "${WS}/install/setup.bash"\n\
    cd "${WS}"\n\
fi\n\
alias s=". ./install/setup.bash"\n\
alias l="clear"' >> /root/.bashrc

# install packages

RUN apt update -y

# RUN DEBIAN_FRONTEND=noninteractive apt install -y gcc-arm-none-eabi gdb-arm-none-eabi stlink-tools openocd
RUN DEBIAN_FRONTEND=noninteractive apt install -y iproute2 net-tools iputils-ping
RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-pip python3-venv
RUN DEBIAN_FRONTEND=noninteractive apt install -y vim nano

RUN python3 -m pip install setuptools==58.2.0

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-colcon-common-extensions
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-rmw-cyclonedds-cpp

# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-slam-toolbox
# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-navigation2
# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-nav2-bringup
# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-rtabmap-ros

RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-joint-state-publisher-gui

RUN rm -rf /ros_entrypoint.sh