FROM beevelop/nodejs

# workspace setup

ENV ROS_DISTRO=galactic
ENV WS="/workspace"

RUN echo '\
if [ -f "/opt/ros/${ROS_DISTRO}/setup.bash" ]; then\n\
    source "/opt/ros/${ROS_DISTRO}/setup.bash"\n\
fi\n\
if [ -f "${WS}/install/setup.bash" ]; then\n\
    source "${WS}/install/setup.bash"\n\
    cd "${WS}"\n\
fi\n\
alias s=". ./install/setup.bash"\n\
alias l="clear"' >> /root/.bashrc

# install ROS2

RUN apt update -y && apt install -y locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN export LANG=en_US.UTF-8

RUN apt install -y software-properties-common
RUN add-apt-repository universe

RUN apt update -y && apt install -y curl
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt remove -y nodejs

RUN apt update -y && apt upgrade -y

RUN apt install -y ros-${ROS_DISTRO}-ros-base ros-dev-tools

# install ROS1

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

RUN apt update -y
RUN apt install -y ros-noetic-ros-base

# install packages

RUN DEBIAN_FRONTEND=noninteractive apt install -y iproute2 net-tools iputils-ping
RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-pip python3-venv
RUN DEBIAN_FRONTEND=noninteractive apt install -y vim nano

RUN python3 -m pip install setuptools==58.2.0

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-colcon-common-extensions
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-rmw-cyclonedds-cpp
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-ros1-bridge

# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-slam-toolbox
# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-navigation2
# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-nav2-bringup
# RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-rtabmap-ros

RUN rm -rf /ros_entrypoint.sh
