odom:
    ros__parameters:
        r: 0.07              # wheel radius
        lx: 0.37             # half of the distance between front wheel and rear wheel
        ly: 0.30             # half of the distance between front wheels
