/**:
    ros__parameters:
        publish_odom: true                                   # publishing odom if true
        odom_pub: odom                                       # output odometry topic
        cmd_vel_sub: cmd_vel                                 # input cmd_vel topic (from high level)
        cmd_vel_pub_left_topic: drive_controller/cmd_vel_l   # output cmd_vel_left topic
        cmd_vel_pub_right_topic: drive_controller/cmd_vel_r  # output cmd_vel_right topic
        ticks_left_topic: drive_controller/ticks_left        # output topic with motors velocities values in rad/s
        ticks_right_topic: drive_controller/ticks_right      # output topic with odometry poses in ticks and odometry velocities in rad/s
        # pid_sub_topic: drive_controller/pid                # topic with PID-terms from keyboard handler
        reset_sub_topic: drive_controller/reset              # odom reset topic from keyboard handler
        r: 0.0323                                            # wheel radius 0.03239
        l: 0.2437                                            # distance between wheels 0.24
        kl: 1.0                                              # linear odometry scale coefficient 0.96
        ka: 1.0                                              # angular odometry scale coefficient 0.95
        ticks: 330.0                                         # number of ticks per one rotation
        frame_id: odom                                       # odom frame id
        child_frame_id: base_footprint                       # child frame id for odom frame
        kp: 2.0                                              # P-term of PID regulator
        ki: 0.0                                              # I-term of PID regulator
        kd: 0.1                                              # D-term of PID regulator
        limit_vels: false                                    # limiting x and theta velocities if true
        max_x_vel: 0.0                                       # linear velocity limit
        max_yaw_vel: 0.0                                     # angular velocity limit
