drive_controller_serial:
    ros__parameters:
        port: "/dev/ttyACM1"                      # arduino port
        baudrate: 2000000                         # baudrate for arduino
        cmd_size: 19                              # msg size from linux
        msg_size: 67                              # msg size from arduino
        receive_time: 100                         # delay after receiving msg from arduino
        pub_topic: "/serial/drive_controller/pub" # topic name for arduino receiver
        sub_topic: "/serial/drive_controller/sub" # topic name for arduino sender
