serial_bridge:
    ros__parameters:
        pose_num: 4                # number of poses in serial msg
        pose_size: 8               # size of each pose in serial msg
        vel_num: 4                 # number of velocities in serial msg
        vel_size: 4                # size of each velocity in serial msg
        serial_pub: "/serial/sub"  # topic for sending transformed msgs to arduino
        serial_sub: "/serial/pub"  # topic for transform serial msgs from arduino
        odom_pub: "/motors/odom"   # topic for pose odometry
        vel_sub: "/motors/cmd_vel" # topic with velocity commands from nav stack
